version: '3.8'

services:
  directus:
    image: directus/directus:latest
    ports:
      - 8055:8055
    environment:
      SECRET: 'fglfjfkfkfgkfgfllmrtrrttl'
      DB_CLIENT: 'postgres'
      DB_HOST: 'database'
      DB_PORT: 5432
      DB_DATABASE: 'directus'
      DB_USER: 'directus'
      DB_PASSWORD: 'directus'
    depends_on:
      - database

  database:
    image: 'postgres:13'
    environment:
      POSTGRES_DB: 'directus'
      POSTGRES_USER: 'directus'
      POSTGRES_PASSWORD: 'directus'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
